### ISSUE TITLE
Transfer should be called on ARB token contract, not on Claim contract

### ISSUE THREAD

**Issue by fala13** [chewonithard/claimArbTokens#1]
ARB ERC20 contract is 0x912CE59144191C1204E64559FE8253a0e49E6548

The code tries to run transfer on Claim contract:
https://github.com/chewonithard/claimArbTokens/blob/3cc3f35f7b54c4c6429ea763f908ec0e0d86b8be/claim.js#L64

Btw. did you test it? I'm having hard time because forks in hardhat and anvil mess up L1&L2 block numbers.

**Comment by giraffe0x** [comment]
Thanks for the catch! 

I've tried to test it on a mock claim contract, it should work but i'm not 100% confident
