### ISSUE TITLE
NONCE ISSUE

### ISSUE THREAD

**Issue by chimmykk** [chewonithard/claimArbTokens#2]
I think instead of getting the nonce real-time one should already check for the nonce and keep it sign and then let the txn go through. The competition here is about who get's to sign/verify first. So it's better to have a pre-signed txn with claim and transaction (with the latest nonce) That will beat it

**Comment by giraffe0x** [comment]
That’s a good point! Let me try and do that

**Comment by giraffe0x** [comment]
Updated script
